on: push

jobs:
  automated-api-tests:
    runs-on: ubunto-latest
  steps:
    - uses: actions/checkout@v3
    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    - name: Run API tests
      run: |
        postman collection run "1022049-ef065d09-5dc5-486c-89da-d678fff65f2d"
